nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
  lfe:
    npmAlwaysAuth: true
    npmRegistryServer: "https://git.saikou.luogu.org.cn/api/v4/packages/npm/"
